services:
  discord-bot:
    build:
      context: ./discord
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
  telegram-bot:
    build:
      context: ./telegram
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
  postgres:
    env_file: .env
    image: postgres:14-alpine
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data:cached
    ports: 
      - ${POSTGRES_PORT}:5432
volumes:
  postgres_data:
